spring:
  profiles:
    default: development
    active: development 

---

spring:
  profiles: development
  
security:
  basic:
    enabled: false
  
# context Path
server:
    port: 9080   
       
---

spring:
  profiles: test
  
# context Path
server:
    port: 9080

---

spring:
  profiles: production
  
# context Path
server:
    port: 9080

---
# common properties for yaml 

# context Path
server:
      contextPath: /prime-finder-api/v1.0
