spring:
  mvc:
    async:
      request-timeout: ${asyncRequestTimeout}

security:
  basic:
    enabled: ${securityEnabled}

# context Path
server:
  servlet:
    context-path: /${context}/${version}
  port: ${serverPort}
logging:
  level:
    root: ${logLevelRoot}
    com:
      nw: ${logLevelApp}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

executor:
  threadpool:
    request:
      coreSize: ${executorCoreSizeRequest}
      maxSize: ${executorMaxSizeRequest}
      queueSize: ${executorQueueSizeRequest}
    primes:
      coreSize: ${executorCoreSizePrimes}
      maxSize: ${executorMaxSizePrimes}
      queueSize: ${executorQueueSizePrimes}
